#! /bin/sh

#Auto start

./fehbg &

sxhkd &

# Monitors
bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 0
bspc monitor HDMI-1 -d 1 2 3 4 5 6 7 8 9 0

# Gap
bspc config window_gap                    20
bspc config top_padding                   20
bspc config bottom_padding                20
bspc config left_padding                  20
bspc config right_padding                 20

# Border
bspc config border_width                  5
bspc config normal_border_color           "#625e55"
bspc config active_border_color           "#625e55"
bspc config focused_border_color          "#8e6f57"
bspc config presel_feedback_color         "#d75f5f"
bspc config single_monocle                false
bspc config split_ratio                   0.50
bspc config borderless_monocle            false
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config pointer_follows_focus         true
bspc pointer_follows_monitor              true

bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config remove_unplugged_monitors     true
bspc config merge_overlapping_monitors    true

bspc config click_to_focus                false
bspc config pointer_modifier              mod4
bspc config pointer_action1               move
bspc config pointer_action3               resize_side
bspc config pointer_action3               resize_corner

